manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects

# display
    - name: Beedle
      url-base: https://github.com/Beedle
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
# display
    - name: middle-earth-nice-view
      remote: Beedle
      revision: main
  self:
    path: config
